spring.application.name=consumer
spring.rabbitmq.addresses=${RMQ_HOST:localhost}:${RMQ_PORT:5672}
spring.rabbitmq.username=${RMQ_User:guest}
spring.rabbitmq.password=${RMQ_Pass:guest}
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.prefetch=1
logging.file.name=logs/app.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7