spring.application.name=producer
spring.rabbitmq.addresses=${RMQ_HOST:localhost}:${RMQ_PORT:5672}
spring.rabbitmq.username=${RMQ_User:guest}
spring.rabbitmq.password=${RMQ_Pass:guest}
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.prefetch=1